version: "3.8"

networks:
  generic-network:
    external: true

services:
  frontend-dev:
    container_name: generic-react
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./app/generic-front:/app
    ports:
      - "8025:8025"
    restart: unless-stopped
    networks:
      generic-network:
        ipv4_address: 172.21.0.4